import { LegalPage } from "@/components/LegalPage";

export default function TermsPage() {
  return <LegalPage title="Terms and Conditions" sections={[
    { heading: "Introduction", paragraphs: ["Welcome to Nexiv. These Terms and Conditions govern your use of our website and the creative and digital services we provide. By accessing our website or engaging our services, you agree to be bound by these terms."] },
    { heading: "Service Agreement", paragraphs: ["The services provided by Nexiv are subject to a separate agreement or contract. These agreements outline the scope of work, timelines, deliverables, and any additional terms specific to the services being provided. These Terms and Conditions apply to general website use and complement, but do not replace, individual signed agreements."] },
    { heading: "Use of Website", paragraphs: ["Visitors may browse the website for informational purposes. Content on this site (text, images, branding, illustrations) is the property of Nexiv and may not be copied, reproduced, or redistributed without written permission."] },
    { heading: "Intellectual Property", paragraphs: ["All intellectual property rights, including copyrights and trademarks, related to the designs, websites, and other creative works produced by Nexiv belong to the company unless otherwise stated in a separate agreement. Ownership of final deliverables transfers to the client only upon full payment, as specified in the relevant project agreement. Nexiv reserves the right to showcase completed work in its portfolio unless otherwise agreed with the client."] },
    { heading: "Client Responsibilities", paragraphs: ["Clients are responsible for providing accurate and complete information necessary for the provision of our services. Clients also have the responsibility to review and approve deliverables within the specified timeframes; delays in feedback or approval may affect project timelines."] },
    { heading: "Payments", paragraphs: ["Payment terms, deposits, and schedules will be outlined in individual project agreements or invoices. Work may be paused or withheld until payment terms are met, as specified in the relevant agreement."] },
    { heading: "Limitation of Liability", paragraphs: ["Nexiv shall not be held liable for any direct, indirect, incidental, consequential, or special damages arising out of or in connection with the use or inability to use our services, including but not limited to loss of data, loss of profits, or business interruption."] },
    { heading: "Third-Party Links", paragraphs: ["Our website may contain links to external websites that are not operated by us. We are not responsible for the privacy practices or content of those third-party websites, and we encourage you to review their policies when visiting them."] },
    { heading: "Changes to These Terms", paragraphs: ["Nexiv reserves the right to modify or update these Terms and Conditions at any time. Any changes will be effective upon posting the revised terms on our website. We encourage you to review this page periodically for updates."] },
    { heading: "Governing Law and Jurisdiction", paragraphs: ["These Terms and Conditions shall be governed by and interpreted in accordance with the laws of Malawi. Any disputes arising from these terms shall be subject to the exclusive jurisdiction of the courts of Malawi."] },
    { heading: "Contact", paragraphs: ["For questions about these Terms and Conditions, contact us at nexiv25@gmail.com or (+265) 0 884 288 849."] },
  ]} />;
}
